In [5]:
import pandas as pd
import numpy as np
print("🔥 igneous")
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

🔥 igneous
Pandas: 3.0.6
NumPy: 2.5.4

In [6]:
df = pd.read_csv("../sample_viirs_snpp_071223.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 74605
Columns: 14

In [8]:
df.columns

Index(['latitude', 'longitude', 'bright_ti4', 'scan', 'track', 'acq_date',
       'acq_time', 'satellite', 'instrument', 'confidence', 'version',
       'bright_ti5', 'frp', 'daynight'],
      dtype='str')

In [9]:
df.head

<bound method NDFrame.head of        latitude  longitude  bright_ti4  scan  track    acq_date  acq_time  \
0       0.05836   29.59085      295.64  0.38   0.59  2023-07-12         3
1       0.48765   31.50760      296.73  0.51   0.66  2023-07-12         3
2       2.15227   13.94524      305.26  0.51   0.49  2023-07-12         3
3       2.15681   13.94618      319.05  0.51   0.49  2023-07-12         3
4       2.15754   13.94131      301.13  0.51   0.50  2023-07-12         3
...         ...        ...         ...   ...    ...         ...       ...
74600  61.42408 -110.40578      350.48  0.40   0.40  2023-07-12      1950
74601  61.42510 -110.39867      336.03  0.40   0.40  2023-07-12      1950
74602  61.42733 -110.40780      328.53  0.40   0.40  2023-07-12      1950
74603  61.42834 -110.40069      338.45  0.40   0.40  2023-07-12      1950
74604  61.42936 -110.39356      339.52  0.40   0.40  2023-07-12      1950

      satellite instrument confidence version  bright_ti5    frp daynight
0             N      VIIRS          n  2.0NRT      275.15   0.83        N
1             N      VIIRS          n  2.0NRT      275.15   0.56        N
2             N      VIIRS          n  2.0NRT      287.94   1.08        N
3             N      VIIRS          n  2.0NRT      288.77   1.81        N
4             N      VIIRS          n  2.0NRT      288.17   1.81        N
...         ...        ...        ...     ...         ...    ...      ...
74600         N      VIIRS          n  2.0URT      309.39  16.01        D
74601         N      VIIRS          l  2.0URT      308.08  32.98        D
74602         N      VIIRS          n  2.0URT      298.15  16.01        D
74603         N      VIIRS          n  2.0URT      302.81  32.98        D
74604         N      VIIRS          n  2.0URT      306.58  32.98        D

[74605 rows x 14 columns]>

In [10]:
df.head()

,latitude,longitude,bright_ti4,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_ti5,frp,daynight
0,0.05836,29.59085,295.64,0.38,0.59,2023-07-12,3,N,VIIRS,n,2.0NRT,275.15,0.83,N
1,0.48765,31.50760,296.73,0.51,0.66,2023-07-12,3,N,VIIRS,n,2.0NRT,275.15,0.56,N
2,2.15227,13.94524,305.26,0.51,0.49,2023-07-12,3,N,VIIRS,n,2.0NRT,287.94,1.08,N
3,2.15681,13.94618,319.05,0.51,0.49,2023-07-12,3,N,VIIRS,n,2.0NRT,288.77,1.81,N
4,2.15754,13.94131,301.13,0.51,0.50,2023-07-12,3,N,VIIRS,n,2.0NRT,288.17,1.81,N

In [11]:
print("Missing values:")
print(df.isna().sum())

Missing values:
latitude      0
longitude     0
bright_ti4    0
scan          0
track         0
acq_date      0
acq_time      0
satellite     0
instrument    0
confidence    0
version       0
bright_ti5    0
frp           0
daynight      0
dtype: int64

In [12]:
df[["latitude", "longitude", "bright_ti4", "bright_ti5", "frp", "scan", "track"]].describe()

,latitude,longitude,bright_ti4,bright_ti5,frp,scan,track
count,74605.000000,74605.000000,74605.00000,74605.000000,74605.000000,74605.000000,74605.000000
mean,10.007627,8.261063,334.42672,297.323856,11.357923,0.458306,0.484713
std,30.337974,72.746193,18.18826,9.801624,22.482901,0.085264,0.105872
min,-77.527320,-164.053510,208.00000,239.210000,0.000000,0.300000,0.360000
25%,-10.572910,13.905160,328.91000,291.070000,2.900000,0.400000,0.400000
50%,-7.122010,19.049590,336.20000,298.840000,5.520000,0.440000,0.450000
75%,52.978350,27.766620,345.09000,302.750000,10.520000,0.510000,0.560000
max,71.092120,178.796550,367.00000,385.310000,584.090000,0.800000,0.800000